### ISSUE TITLE
Crash on Beatmap Load

### ISSUE THREAD

**Issue by MLisDreaming** [GSculerlor/Cytosu#13]
The game crashes as soon as beatmap finishes loading if the latest compile of Cytosu is used on the latest version of osu!lazer (2020.1121.0).

**Comment by GSculerlor** [comment]
Thank you for reporting. I'll check it later today

**Comment by GSculerlor** [comment]
should not be an issue anymore. feel free to reopen if you somehow can reproduce the issue
