### ISSUE TITLE
How to fix it

### ISSUE THREAD

**Issue by yarik303** [GSculerlor/Cytosu#41]
![image](https://user-images.githubusercontent.com/75032600/123240813-4e3cad80-d4e9-11eb-9249-9ddd20feb280.png)
osu!lazer version 2021.623.0

**Comment by GSculerlor** [comment]
this is because Cytosu used an outdated osu!lazer version. will do a version bump and create a release later today

**Comment by GSculerlor** [comment]
should be fixed on latest release (https://github.com/GSculerlor/Cytosu/releases/tag/2021.625.0). please reopen this issue if the error still persists.
