### ISSUE TITLE
Gameplay Cursor changes to Menu Cursor

### ISSUE THREAD

**Issue by enoslayd** [GSculerlor/Cytosu#8]
Gameplay Cursor changes to Menu Cursor when the cursor is positioned near the top (score display) or bottom (density graph)

Top:
![osu_2020-08-17_16-12-53](https://user-images.githubusercontent.com/41866328/90373716-f2bdba00-e0a4-11ea-93ea-4f6f599301c5.png)

Bottom:
![osu_2020-08-17_16-13-17](https://user-images.githubusercontent.com/41866328/90373773-0a953e00-e0a5-11ea-9ad8-b58f29763d34.png)

**Comment by GSculerlor** [comment]
Pointed that out, will push the patch later today!

**Comment by GSculerlor** [comment]
Fixed on 3ebac141ac9ed0aa00a059ed4a272ca6f5d2bfc3, please give a try on latest commit

![1597659897970](https://user-images.githubusercontent.com/6506864/90386407-ba22de00-e0ae-11ea-8650-77a77e91a35f.gif)

**Comment by enoslayd** [comment]
ok thanks!
